config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pets do 
    resources :reports 
  end
  root to: "pets#index"
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
    # belongs_to :owner, class_name: "User", foreign_key: :user_id
   
    belongs_to :user
    has_one_attached :image
    has_many :reports
    
    
end

app/models/report.rb
class Report < ApplicationRecord
    belongs_to :pet 
    belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pets
  has_many :reports
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    # before_action :authenticate_user!
    protect_from_forgery with: :exception
    
        # Prevent CSRF attacks by raising an exception.
        # For APIs, you may want to use :null_session instead.
     
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

def index
    @owners = Owner.all
end


def show
    @owner = Owner.find(params[:id])
end

def new
    @owner = Owner.new
end

def create
    @owner = owner.new(owner_params)

    if @owner.save
        redirect_to owners_path, notice: 'Your Profile was succesfully created.'
    else
        render :new
    end
end

def edit
    @owner = Owner.find(params[:id])
end

def update
    owner = Owner.find(params["id"])
    owner.update(owner_params)
    redirect_to owners_path
end

def destroy
    

    Owner.find(params["id"]).destroy
    redirect_to owners_path
    
end
# def create
#     # burger es variable de la clase hamburguesa
#     burger = Burger.create(burger_params)
#     redirect_to burger
# end

private

def owner_params
    params.require(:owner).permit(:name, :lastname, :phone, :email, :image)
end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

    def index
        @pets = Pet.all.order('created_at desc')
    end


    def show
        
        @pet = Pet.find(params[:id])
    end

    def new
        
        @pet = Pet.new
    end

    def create

        @pet = current_user.pets.new(pet_params)
         latlong = Geocoder.search(params[:pet][:last_seen]).first.coordinates
         @pet.longitude = latlong[1]
         @pet.latitude = latlong[0]

        if @pet.save
            redirect_to pets_path, notice: 'Your Pet was succesfully created.'
        else
            render :new
        end
    end

    def edit
        
        @pet = Pet.find(params[:id])
    end

    def update

        pet = Pet.find(params["id"])
        latlong = Geocoder.search(params[:pet][:last_seen]).first.coordinates
         pet.longitude = latlong[1]
         pet.latitude = latlong[0]
        pet.update(pet_params)
        redirect_to pets_path
    end

    def destroy
        

        Pet.find(params["id"]).destroy
        redirect_to pets_path
        
    end
    # def create
    #     # burger es variable de la clase hamburguesa
    #     burger = Burger.create(burger_params)
    #     redirect_to burger
    # end

    private

    def pet_params
        params.require(:pet).permit(:name, :category, :last_seen, :breed, :color, :characteristic, :image, :date_lost, :status)
    end

    end

    

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

    def index 
      
    end

    def new
      @report = Report.new
      @pet = Pet.find(params[:pet_id])
    end

    def create
       @report = Report.new(report_params)
       @report.user_id = current_user.id
       @report.pet_id = params[:pet_id] 

       latlong = Geocoder.search(params[:report][:place]).first.coordinates
         @report.longitude = latlong[1]
         @report.latitude = latlong[0]

       if @report.save 
        redirect_to "/pets/#{params[:pet_id]}/"
        flash[:notice] = "Report saved"
       else
        redirect_back(fallback_location: "/")
        flash[:alert] = "No report"
        end

    end

    def show
        @report = Report.find(params[:id])
        
    end

    private

    def report_params
        params.require(:report).permit(:user_id, :last_seen, :latitude, :longitude, :comment, :place)
    end
    
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:lastname, :phone, :date_of_birth])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:lastname, :phone, :date_of_birth])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Findmypet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
   
   <script>
   $(document).ready(function() {
     $('#myModal').modal('show')


   });
   </script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>  
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
<script src='//underscorejs.org/underscore-min.js' type='text/javascript'></script>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>


 
<a href="pets#index" class="navbar-brand" >
  <%= link_to image_tag("pet-icon-png-13.jpg", alt: "Brand",:size => "50x50"), pets_path, :class=>'navbar-brand' %>
    
</a>



     <% if user_signed_in? %>
         Logged in as <strong><%= current_user.name %></strong>
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>   |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>   |
        <%= link_to "Add a missing pet", "/pets/new" ,:class => 'navbar-link'  %>
        
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>   |
       



<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bd-example-modal-sm">Have you lost your pet?</button>

<div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id=#myModal>
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <p></p>
      <h6  class="font-weight-light"> Have you lost your pet? </h6>
      <h6  class="font-weight-light"> Sign Up or Login to continue!! </h6>     

        <%= link_to "Sign up", new_user_registration_path,class:"btn btn-outline-primary btn-xs"   %> 
        <p></p>  
        <%= link_to "Login", new_user_session_path,class:"btn btn-outline-success btn-xs" %>

    </div>
  </div>
</div>
    <% end %>


    <%= yield %>
  <footer class="page-footer font-small blue">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/"> Alexandra Osorio</a>
  </div>
  <!-- Copyright -->

</footer>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="container">


  <%= form_with model: @pet do |form | %>

<form class="form-horizontal">
    <div class="form-group">
    <p> 
        <label class="control-label col-sm-2"> Name:</label>
        <%= form.text_field :name  %>
    </P>
    </div>
    <div class="form-group">
    <p> 
        <label class="control-label col-sm-2"> Last Seen:</label>
        <%= form.text_field :last_seen  %>
    </P>
    </div>
    
    <div class="form-group">
    <p>
        <label class="control-label col-sm-2"> Category:</label>
        <%= form.select :category,['Cat','Dog','Bird']  %>
    </p>
    </div>

    <div class="form-group">
      <p>
        <label class="control-label col-sm-2"> Breed:</label>
        <%= form.text_field :breed  %>
      </p>
    </div>

    <div class="form-group">
     <p>
        <label class="control-label col-sm-2"> Color:</label>
        <%= form.text_field :color  %>
    </p>
    </div>

    <div class="form-group">
      <p>
        <label class="control-label col-sm-2"> Characteristic:</label>
        <%= form.text_field :characteristic  %>
      </p>
    </div>


    <div class="form-group">
    <p>
    <label class="control-label col-sm-2"> Image:</label>
    <%= form.file_field :image %>
    </p>
    </div>

    <div class="form-group">
      <p>
        <label class="control-label col-sm-2"> Date Lost:</label>
        <%= form.date_field :date_lost  %>
      </p>
    </div>

    <div class="form-group">
      <p>
        <label class="control-label col-sm-2"> Is your pet lost?</label>
        <%= form.check_box :status  %>
      </p>
    </div>


    <div class="actions">
    <%= form.submit "Create Pet", class:"btn btn-outline-success"%>
    <%= link_to 'Back', pets_path, class:"btn btn-outline-secondary"%>

    </div>

<%end%>
</div>
<h1></h1>

app/views/pets/edit.html.erb
<% if current_user.id == @pet.user_id %>
    <h1 class= "deepshd" style= "text-align:center"><%= "Edit Pet "%> </h1>
    <%= render 'form', pet: @pet %>

<% else %>
    <h1>You don't have access to edit this pet!!</h1>
<% end %>
    

app/views/pets/index.html.erb
<h1 style= "text-align: center"; class="deepshd">Lost Pets</h1>
<p>

</p>
  <div class="container">
    <div class="row">    
      <% @pets.each do |pet| %>
        <tr id="center-cards">
            <div class="col-sm">   
              <div class="card",class="flex-container" style="width: 18rem;">
                  <%= image_tag(pet.image, style: "width: 100px", height:"100px", id:"center-cards", class:"img-rounded" ) %>
                  <div class="card-body",class="flex-container">
                      <h5 id="left-cards"><%= "Name: #{pet.name}" %></h5>
                      <p class="card-text"> <%= "Date Lost: #{pet.date_lost}" %></p>
                      <a><%= link_to 'See Details', pet, :class => "button btn btn-info",  id:"center-cards" %> </a>
                      
                  </div>
              </div>
      <p></p>
             </div>
          </tr>
      <% end %>
    </div>
  </div> 

 
  <a><%= link_to 'Add a missing Pet', new_pet_path, :class => "button btn btn-info",  id:"center-cards" %> </a>

  

app/views/pets/new.html.erb
<h1 class= "deepshd" style= "text-align:center"><%= "New Register"%> </h1>
<%= render 'form' %>

app/views/pets/show.html.erb
<%# <%= @pet.inspect %> 

    <div> </div>
    <div> </div>
    <div> </div>
    <div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-6">
        <%# <%= "Name:" %> 
       <div class="deepshd2" style= "text-align:center">
        <h2> <%= @pet.name %> </h2>
      <p></p>
        <div> </div>
       </div>

       <div style= "text-align:center">
      <%= image_tag(@pet.image, style: "width: 200px", class: "rounded") %>
      <div> </div>
   

        <%= "Category:" %>
        <%=  @pet.category %>
        <div> </div>
        <%= "Breed:"%>
        <%= @pet.breed %>
        <div> </div>
        <%= "Color:"%>
        <%= @pet.color %>
        <div> </div>
        <%= "Characteristic:"%>
        <%= @pet.characteristic %>
        <div> </div>
        <%= "Owner:"%>
        <%= @pet.user.name %>
        <div> </div>
        <%= "Date Lost:"%>
        <%= @pet.date_lost %>
        <div> </div>
        <%= "Last seen:"%>
        <%= @pet.last_seen %>
        <div> </div>
    </div>
    </div>
 
     <div class="col-sm-3 col-md-6">
      <div id="map" style="width:100%;height:300px;"></div>

    </div>
      </div>
    <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: <%= @pet.latitude %>, lng: <%= @pet.longitude %>},
          zoom: 15
        });
          var marker = new google.maps.Marker(document.getElementById('map'), {
              position: {lat: <%= @pet.latitude %>, lng: <%= @pet.longitude %>}});
      }
      
    </script>


    

    
<p> </p>
 <h1 class="deepshd" style= text-align:center> Last Seen Reports </h1>
 <p> </p>
<div class="container">
<table class="table-striped"  >
  <thead style= text-align:center >
  
    <tr>
      <th>Who made the report </th>
      <th>When? </th>
      <th>Where?  </th>
      <th>Comment</th>
      <th colspan="5"></th>
      
    </tr>
  </thead>

  <tbody style= text-align:center;>
    <% @pet.reports.each do |report| %>
      <tr>
        <td><%= report.user.name%></td>
        <td><%= report.last_seen %></td>
        <td><%= report.place %></td>
        <td><%= report.comment %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

     <% if user_signed_in? && current_user.id == @pet.user.id %>
       <%= link_to "Edit", "/pets/#{params[:id]}/edit",class:"btn btn-outline-primary" %>       
       
        <%= link_to "New Report", "/pets/#{params[:id]}/reports/new",class:"btn btn-outline-success"%>     
        
       <%= link_to 'Back', pets_path,class:"btn btn-outline-secondary"%>
     <% elsif user_signed_in? %>
        <%= link_to "New Report", "/pets/#{params[:id]}/reports/new",class:"btn btn-outline-success" %>   
        
        <%= link_to 'Back', pets_path, class:"btn btn-outline-secondary"%>
    <% elsif %>
        <p></p>
        <h5  class="font-weight-light" style="color:red"> Please Log In to add a report! </h5>
    
    <% end %>
    
 <script async defer src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['API_KEY']%>&callback=initMap"
  type="text/javascript"></script>



    

app/views/reports/index.html.erb
<%= link_to "New Report", "/pets/#{params[:pet_id]}/reports/new" %>

app/views/reports/new.html.erb
<%= form_for [@pet,@report] do |form|%>
   
<div class="container">
<h1 class= "deepshd" style= "text-align:center"><%= "Did you saw #{@pet.name}?"%> </h1>
<p>

</p>
<form class="form-horizontal">
    <div class="form-group">
        <label class="control-label col-sm-2"> When?</label>
        <%= form.date_field :last_seen%>
    </div>
    <div></div>
    <label class="control-label col-sm-2"> Place:</label>
    <%= form.text_field :place%>
    <div></div>
    
    <label class="control-label col-sm-2" > Comment:</label>
    <%= form.text_area :comment%>

    <p> </P>
    <div class="actions">
   
    <%= form.submit "Create Report", class:"btn btn-outline-success"%>
<% end %>

       <%= link_to 'Back', pets_path,class:"btn btn-outline-secondary"%>

   

app/views/reports/show.html.erb
    <div></div>
   <label > Name:</label>
    <%= @report.pet.name%>
    <div></div>
    <label > When?</label>
    <%= @report.last_seen%>
    <div></div>
    <label > Latitude</label>
    <%= @report.latitude%>
    <div></div>
    <label > Longitude</label>
    <%= @report.longitude%>
    <div></div>
    <label > comment</label>
    <%= @report.comment%>
    <div></div>
  
    <%= link_to 'Back', pets_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name),class:"btn btn-secondary btn-block" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class:"btn btn-secondary btn-block" %><br />
   
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>